name = "NMRInversions"
uuid = "55c20db2-0166-4687-95c3-62a9c7afb29b"
authors = ["Aristarchos Mavridis <aris.mav@hotmail.com>"]
version = "1.0.0-DEV"

[deps]
DelimitedFiles = "8bb1440f-4735-579b-a4ab-409b98df4dab"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
NativeFileDialog = "e1fe445b-aa65-4df4-81c1-2041507f0fd4"
Optimization = "7f7a1694-90dd-40f0-9382-eb1efda571ba"
OptimizationOptimJL = "36348300-93cb-4f02-beb5-3c3902f8871e"
Pkg = "44cfe95a-1eb2-52ea-b672-e2afdf69b78f"
PolygonOps = "647866c9-e3ac-4575-94e7-e3d426903924"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"

[weakdeps]
GLMakie = "e9467ef8-e4e7-5192-8a1a-b1aee30e663a"
JuMP = "4076af6c-e467-56ae-b986-b466b2749572"
QuadraticModels = "f468eda6-eac5-11e8-05a5-ff9e497bcd19"
RipQP = "1e40b3f8-35eb-4cd8-8edd-3e515bb9de08"

[extensions]
gui_ext = "GLMakie"
tikhonov_jump_ext = "JuMP"
tikhonov_ripqp_ext = ["RipQP", "QuadraticModels"]

[compat]
GLMakie = "0.10"
Optimization = "3"
julia = "1.9.0"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
